# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created: Thu Nov 18 04:08:33 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 625)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.Tabcourses = QtGui.QWidget()
        self.Tabcourses.setObjectName("Tabcourses")
        self.gridLayout_2 = QtGui.QGridLayout(self.Tabcourses)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget = QtGui.QTreeWidget(self.Tabcourses)
        self.treeWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout_2.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Tabcourses, "")
        self.TabEdit = QtGui.QWidget()
        self.TabEdit.setObjectName("TabEdit")
        self.gridLayout_3 = QtGui.QGridLayout(self.TabEdit)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit = QtGui.QTextEdit(self.TabEdit)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.TabEdit)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.courseComboBox = QtGui.QComboBox(self.groupBox)
        self.courseComboBox.setObjectName("courseComboBox")
        self.verticalLayout.addWidget(self.courseComboBox)
        self.titleLineEdit = QtGui.QLineEdit(self.groupBox)
        self.titleLineEdit.setObjectName("titleLineEdit")
        self.verticalLayout.addWidget(self.titleLineEdit)
        self.gridLayout_3.addWidget(self.groupBox, 0, 1, 1, 1)
        self.tabWidget.addTab(self.TabEdit, "")
        self.TabTodo = QtGui.QWidget()
        self.TabTodo.setObjectName("TabTodo")
        self.gridLayout_5 = QtGui.QGridLayout(self.TabTodo)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.TodoList = QtGui.QTreeWidget(self.TabTodo)
        self.TodoList.setIndentation(0)
        self.TodoList.setObjectName("TodoList")
        self.TodoList.header().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.TodoList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.TabTodo, "")
        self.Tabschedule = QtGui.QWidget()
        self.Tabschedule.setObjectName("Tabschedule")
        self.gridLayout_4 = QtGui.QGridLayout(self.Tabschedule)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget = QtGui.QTableWidget(self.Tabschedule)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Tabschedule, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea(QtCore.Qt.TopToolBarArea), self.toolBar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionCourse = QtGui.QAction(MainWindow)
        self.actionCourse.setObjectName("actionCourse")
        self.actionLecture = QtGui.QAction(MainWindow)
        self.actionLecture.setObjectName("actionLecture")
        self.actionviewCourses = QtGui.QAction(MainWindow)
        self.actionviewCourses.setObjectName("actionviewCourses")
        self.actionviewTo_Do_Tasks = QtGui.QAction(MainWindow)
        self.actionviewTo_Do_Tasks.setObjectName("actionviewTo_Do_Tasks")
        self.actionviewSchedule = QtGui.QAction(MainWindow)
        self.actionviewSchedule.setObjectName("actionviewSchedule")
        self.actionviewStatistics = QtGui.QAction(MainWindow)
        self.actionviewStatistics.setObjectName("actionviewStatistics")
        self.actionaddCourse = QtGui.QAction(MainWindow)
        self.actionaddCourse.setObjectName("actionaddCourse")
        self.actionaddLecture = QtGui.QAction(MainWindow)
        self.actionaddLecture.setObjectName("actionaddLecture")
        self.actionaddTask = QtGui.QAction(MainWindow)
        self.actionaddTask.setObjectName("actionaddTask")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionaddCourse)
        self.menuEdit.addAction(self.actionaddLecture)
        self.menuEdit.addAction(self.actionaddTask)
        self.menuView.addAction(self.actionviewCourses)
        self.menuView.addAction(self.actionviewTo_Do_Tasks)
        self.menuView.addAction(self.actionviewSchedule)
        self.menuView.addAction(self.actionviewStatistics)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setSortingEnabled(True)
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Course", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Taught By", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(4, QtGui.QApplication.translate("MainWindow", "Views", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(5, QtGui.QApplication.translate("MainWindow", "Review state", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tabcourses), QtGui.QApplication.translate("MainWindow", "Courses", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Course Infos", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabEdit), QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.TodoList.setSortingEnabled(True)
        self.TodoList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.TodoList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.TodoList.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "State", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabTodo), QtGui.QApplication.translate("MainWindow", "To-Do", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Saturday", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Sunday", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Monday", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Tuesday", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Wednesday", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Thursday", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Friday", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tabschedule), QtGui.QApplication.translate("MainWindow", "Schedule", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCourse.setText(QtGui.QApplication.translate("MainWindow", "Course", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLecture.setText(QtGui.QApplication.translate("MainWindow", "Lecture", None, QtGui.QApplication.UnicodeUTF8))
        self.actionviewCourses.setText(QtGui.QApplication.translate("MainWindow", "Courses", None, QtGui.QApplication.UnicodeUTF8))
        self.actionviewTo_Do_Tasks.setText(QtGui.QApplication.translate("MainWindow", "To-Do Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.actionviewSchedule.setText(QtGui.QApplication.translate("MainWindow", "Schedule", None, QtGui.QApplication.UnicodeUTF8))
        self.actionviewStatistics.setText(QtGui.QApplication.translate("MainWindow", "Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.actionaddCourse.setText(QtGui.QApplication.translate("MainWindow", "Course", None, QtGui.QApplication.UnicodeUTF8))
        self.actionaddLecture.setText(QtGui.QApplication.translate("MainWindow", "Lecture", None, QtGui.QApplication.UnicodeUTF8))
        self.actionaddTask.setText(QtGui.QApplication.translate("MainWindow", "Task", None, QtGui.QApplication.UnicodeUTF8))

